INSERT INTO ORDEN (MESERO, MESA, CLIENTE, FECHA, TOTAL, ACTIVA, COMENTARIO)
VALUES (1001, 10, 'Juan', TO_DATE('2023-05-01', 'YYYY-MM-DD'), 150.50, 1, NULL);

INSERT INTO ORDEN (MESERO, MESA, CLIENTE, FECHA, TOTAL, ACTIVA, COMENTARIO)
VALUES (1002, 5, 'María', TO_DATE('2023-05-02', 'YYYY-MM-DD'), 200.75, 1, NULL);

INSERT INTO ORDEN (MESERO, MESA, CLIENTE, FECHA, TOTAL, ACTIVA, COMENTARIO)
VALUES (1003, 8, 'Pedro', TO_DATE('2023-05-03', 'YYYY-MM-DD'), 80.25, 1, NULL);

INSERT INTO ORDEN (MESERO, MESA, CLIENTE, FECHA, TOTAL, ACTIVA, COMENTARIO)
VALUES (1001, 3, 'Ana', TO_DATE('2023-05-04', 'YYYY-MM-DD'), 120.00, 1, NULL);

INSERT INTO ORDEN (MESERO, MESA, CLIENTE, FECHA, TOTAL, ACTIVA, COMENTARIO)
VALUES (1002, 7, 'Luis', TO_DATE('2023-05-05', 'YYYY-MM-DD'), 180.50, 1, NULL);

---

INSERT INTO CATEGORIA (NOMBRE)
VALUES ('Comida');

INSERT INTO CATEGORIA (NOMBRE)
VALUES ('Bebidas');
---

INSERT INTO PRODUCTO (ID_CATEGORIA, NOMBRE, PRECIO, AREA, INVENTARIO)
VALUES (1, 'Pizza', 10.99, 'C', 50);

INSERT INTO PRODUCTO (ID_CATEGORIA, NOMBRE, PRECIO, AREA, INVENTARIO)
VALUES (1, 'Hamburguesa', 8.99, 'C', 50);

INSERT INTO PRODUCTO (ID_CATEGORIA, NOMBRE, PRECIO, AREA, INVENTARIO)
VALUES (2, 'Refresco', 2.99, 'B', 100);

INSERT INTO PRODUCTO (ID_CATEGORIA, NOMBRE, PRECIO, AREA, INVENTARIO)
VALUES (2, 'Agua', 1.99, 'B', 100);

INSERT INTO PRODUCTO (ID_CATEGORIA, NOMBRE, PRECIO, AREA, INVENTARIO)
VALUES (1, 'Ensalada', 6.99, 'C', 30);

---

INSERT INTO DETALLE_ORDEN (ID_ORDEN, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO)
VALUES (1, 1, 2, 10.99);

INSERT INTO DETALLE_ORDEN (ID_ORDEN, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO)
VALUES (1, 2, 1, 5.99);

INSERT INTO DETALLE_ORDEN (ID_ORDEN, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO)
VALUES (2, 3, 3, 7.99);

INSERT INTO DETALLE_ORDEN (ID_ORDEN, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO)
VALUES (2, 4, 2, 4.99);

INSERT INTO DETALLE_ORDEN (ID_ORDEN, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO)
VALUES (3, 5, 1, 6.99);

INSERT INTO DETALLE_ORDEN (ID_ORDEN, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO)
VALUES (3, 3, 2, 8.99);

INSERT INTO DETALLE_ORDEN (ID_ORDEN, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO)
VALUES (4, 2, 1, 3.99);

INSERT INTO DETALLE_ORDEN (ID_ORDEN, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO)
VALUES (4, 3, 3, 9.99);

INSERT INTO DETALLE_ORDEN (ID_ORDEN, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO)
VALUES (5, 4, 2, 7.99);

INSERT INTO DETALLE_ORDEN (ID_ORDEN, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO)
VALUES (5, 1, 1, 6.99);

---
UPDATE ORDEN SET ACTIVA = 0 WHERE ID_ORDEN = 1;
UPDATE ORDEN SET ACTIVA = 0 WHERE ID_ORDEN = 2;