
CREATE OR REPLACE TRIGGER TRIGGER_ORDEN 
    BEFORE INSERT ON ORDEN FOR EACH ROW 
BEGIN
    :NEW.ID_ORDEN := ORDEN_SEQ.NEXTVAL;
END;

CREATE OR REPLACE TRIGGER TRIGGER_PRODUCTO 
    BEFORE INSERT ON PRODUCTO FOR EACH ROW 
BEGIN
    :NEW.ID_PRODUCTO := PRODUCTO_SEQ.NEXTVAL;
END;

CREATE OR REPLACE TRIGGER TRIGGER_CATEGORIA 
    BEFORE INSERT ON CATEGORIA FOR EACH ROW 
BEGIN
    :NEW.ID_CATEGORIA := CATEGORIA_SEQ.NEXTVAL;
END;