
CREATE OR REPLACE TRIGGER TRG_INS_PRODUCTO_INVENTARIO
    BEFORE INSERT ON PRODUCTO FOR EACH ROW
BEGIN
    IF :NEW.INVENTARIO < 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'El INVENTARIO NO PUEDE SER NEGATIVO.');
    END IF;
END;

CREATE OR REPLACE TRIGGER TRG_UPD_PRODUCTO_INVENTARIO
    BEFORE UPDATE ON PRODUCTO FOR EACH ROW
BEGIN
    IF :NEW.INVENTARIO < 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'EL INVENTARIO NO PUEDE SER NEGATIVO.');
    END IF;
END;

CREATE OR REPLACE TRIGGER TRG_INS_PRODUCTO_AREA
    BEFORE INSERT ON PRODUCTO FOR EACH ROW
DECLARE
    VALOR_AREA PRODUCTO.AREA%TYPE;
BEGIN
    VALOR_AREA := :NEW.AREA;
    IF VALOR_AREA NOT IN ('C', 'B') THEN
        RAISE_APPLICATION_ERROR(-20001, 'EL CAMPO SOLO PERMITE VALORES DE "C" O "B".');
    END IF;
END;

CREATE OR REPLACE TRIGGER TRG_UPD_PRODUCTO_AREA
    BEFORE UPDATE ON PRODUCTO FOR EACH ROW
DECLARE
    VALOR_AREA PRODUCTO.AREA%TYPE;
BEGIN
    VALOR_AREA := NVL(:NEW.AREA, :OLD.AREA);
    IF VALOR_AREA NOT IN ('C', 'B') THEN
        RAISE_APPLICATION_ERROR(-20001,  'EL CAMPO SOLO PERMITE VALORES DE "C" O "B".');
    END IF;
END;


