
CREATE OR REPLACE TRIGGER TGR_NO_ELIMINAR_PARAMETROS BEFORE
    DELETE ON PARAMETROS FOR EACH ROW
BEGIN
    IF :OLD.ID_PARAMETRO IN (1, 2) THEN
        RAISE_APPLICATION_ERROR(-20001, 'NO SE PUEDEN ELIMINAR ESTOS PARAMETROS.');
    END IF;
END;