
CREATE OR REPLACE FUNCTION ACTUALIZAR_TOTAL_ORDEN(ID_PARAMETRO IN NUMBER) RETURN NUMBER AS
    TOTAL_ORDEN NUMBER := 0;
BEGIN
    SELECT SUM(SUBTOTAL) INTO TOTAL_ORDEN FROM DETALLE_ORDEN WHERE ID_ORDEN = ID_PARAMETRO;
    UPDATE ORDEN SET TOTAL = TOTAL_ORDEN WHERE ID_ORDEN = ID_PARAMETRO;
    RETURN TOTAL_ORDEN;
END;